### PR TITLE
Feature/316 fix non breakable chars

### LINKED ISSUE #305: Copybooks that contain 'tabs' and 'spaces' load with errors
## Describe the bug
Some copybooks that are created on a PC may contain TAB characters for indentation instead of spaces. If TABs are present between field name and PIC, the parser prints the following errors:

```
line 2:9 token recognition error at: ' '
line 2:10 token recognition error at: ' '
line 2:11 token recognition error at: ' '
line 2:12 token recognition error at: ' '
line 2:13 token recognition error at: ' '
line 2:14 token recognition error at: ' '
line 2:15 token recognition error at: ' '
```

Sometimes the parser prints these errors on spaces as well.

Here is an example of a copybook that produces errors:
[TEST.cpy.txt](https://github.com/AbsaOSS/cobrix/files/4769844/TEST.cpy.txt)

## To Reproduce
Try to load a copybook that has TAB characters and space.

## Expected behaviour
TAB characters should be considered whitespace and should be ignored. Same for spaces.

### PR DESCRIPTION
**Pull request by yruslan**
Closes #305, #315, #316

### CODE REVIEW

File: cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/antlr/ANTLRParser.scala [hunk 1]
```diff
@@ -74,6 +74,15 @@ object ANTLRParser {
     visitor.ast
   }
 
+  /**
+    * Replace special characters that have semantics of spaces.
+    */
+  private def filterSpecialCharacters(copybook: String): String = {
+    copybook
+      .replace('\u00a0', ' ') // Non-breakable spaces
+      .replace(0x09.toByte.toChar, ' ') // Tabs
```
Comment (Zejnilovic) [inline cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/antlr/ANTLRParser.scala:83]: just curious why use 2 different notation to specify these?

Comment (yruslan) [reply cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/antlr/ANTLRParser.scala:83]: Yeah, seems confusing. Will use the same notation.
